# serverless.yml

service: ti-api-account

custom:
  params:
    userPoolArn: ${ssm:/${opt:stage, 'dev'}/auth/cognito/userPool/arn}
    cognitoUserPool: ${ssm:/${opt:stage, 'dev'}/auth/cognito/userPool/id}
    cognitoClientId: ${ssm:/${opt:stage, 'dev'}/auth/cognito/client/id}
    accountTable: ${ssm:/${opt:stage, 'dev'}/dynamoDB/table/account}
    accountTableArn: ${ssm:/${opt:stage, 'dev'}/dynamoDB/table/account/arn}
    authApi: https://nbvxij0q0h.execute-api.us-east-1.amazonaws.com/${opt:stage, 'dev'}
  corsMethods: 'GET,OPTIONS,POST'
  corsHeaders: 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
  corsOrigins: '*'
  serverless-offline:
    httpPort: 5052
    lambdaPort: 5053
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUTH_API: '${self:custom.params.authApi}'
    ACCOUNT_TABLE: '${self:custom.params.accountTable}'
  stackTags:
    "ti:app": "Toro Investimentos"
    "ti:stage-name": ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:BatchWriteItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:GetRecords'
        - 'dynamodb:PutItem'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:UpdateItem'
      Resource:
        - '${self:custom.params.accountTableArn}'
functions:
  app:
    handler: index.handler
    description: API for manage accounts
    events:
      - http:
          method: GET
          path: '/account/{email}'
          cors: true
          private: false
          authorizer:
            name: authorizer
            arn: ${self:custom.params.userPoolArn}
            scopes:
              - aws.cognito.signin.user.admin
      - http:
          method: POST
          path: '/spb/events'
          cors: true
          private: false
          authorizer:
            name: authorizer
            arn: ${self:custom.params.userPoolArn}
            scopes:
              - aws.cognito.signin.user.admin
package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - src/**
    - ./index.js

plugins:
  - serverless-offline
